 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/total_rentals", type: :request do
  # TotalRental. As you add validations to TotalRental, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TotalRental.create! valid_attributes
      get total_rentals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      total_rental = TotalRental.create! valid_attributes
      get total_rental_url(total_rental)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_total_rental_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      total_rental = TotalRental.create! valid_attributes
      get edit_total_rental_url(total_rental)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TotalRental" do
        expect {
          post total_rentals_url, params: { total_rental: valid_attributes }
        }.to change(TotalRental, :count).by(1)
      end

      it "redirects to the created total_rental" do
        post total_rentals_url, params: { total_rental: valid_attributes }
        expect(response).to redirect_to(total_rental_url(TotalRental.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TotalRental" do
        expect {
          post total_rentals_url, params: { total_rental: invalid_attributes }
        }.to change(TotalRental, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post total_rentals_url, params: { total_rental: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested total_rental" do
        total_rental = TotalRental.create! valid_attributes
        patch total_rental_url(total_rental), params: { total_rental: new_attributes }
        total_rental.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the total_rental" do
        total_rental = TotalRental.create! valid_attributes
        patch total_rental_url(total_rental), params: { total_rental: new_attributes }
        total_rental.reload
        expect(response).to redirect_to(total_rental_url(total_rental))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        total_rental = TotalRental.create! valid_attributes
        patch total_rental_url(total_rental), params: { total_rental: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested total_rental" do
      total_rental = TotalRental.create! valid_attributes
      expect {
        delete total_rental_url(total_rental)
      }.to change(TotalRental, :count).by(-1)
    end

    it "redirects to the total_rentals list" do
      total_rental = TotalRental.create! valid_attributes
      delete total_rental_url(total_rental)
      expect(response).to redirect_to(total_rentals_url)
    end
  end
end
